/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CommunityReactionKind = "dislike" | "like";

export type EditorialPublishStatus = "draft" | "published" | "review";

export type EditorialVerificationStatus = "conflict" | "failed" | "pending" | "review" | "verified";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface CommunityCommentReactions {
  commentId: Int8;
  createdAt: Generated<Timestamp>;
  kind: CommunityReactionKind;
  userId: number;
}

export interface CommunityComments {
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  parentCommentId: Int8 | null;
  postId: Int8;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface CommunityPostReactions {
  createdAt: Generated<Timestamp>;
  kind: CommunityReactionKind;
  postId: Int8;
  userId: number;
}

export interface CommunityPosts {
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  title: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface CommunityProfiles {
  avatarKey: Generated<string>;
  bio: string | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface EditorialItems {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  isRumor: Generated<boolean>;
  itemType: string;
  publishStatus: Generated<EditorialPublishStatus>;
  sourceName: string | null;
  sourcePublishedAt: Timestamp | null;
  sourceUrl: string;
  summary: string;
  team: string;
  title: string;
  updatedAt: Generated<Timestamp>;
  verificationEvidence: Json | null;
  verificationProvider: string | null;
  verificationStatus: Generated<EditorialVerificationStatus>;
  verifiedAt: Timestamp | null;
}

export interface EditorialReviewQueue {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  itemId: Int8;
  reason: string;
  reviewedAt: Timestamp | null;
  reviewedBy: Int8 | null;
}

export interface FeedRefreshState {
  feedKey: string;
  lastRefreshedAt: Timestamp | null;
  refreshStartedAt: Timestamp | null;
  refreshToken: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  communityCommentReactions: CommunityCommentReactions;
  communityComments: CommunityComments;
  communityPostReactions: CommunityPostReactions;
  communityPosts: CommunityPosts;
  communityProfiles: CommunityProfiles;
  editorialItems: EditorialItems;
  editorialReviewQueue: EditorialReviewQueue;
  feedRefreshState: FeedRefreshState;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const CommunityReactionKindArrayValues: [CommunityReactionKind, ...CommunityReactionKind[]] = ["dislike","like"];
export const EditorialVerificationStatusArrayValues: [EditorialVerificationStatus, ...EditorialVerificationStatus[]] = ["conflict","failed","pending","review","verified"];
export const EditorialPublishStatusArrayValues: [EditorialPublishStatus, ...EditorialPublishStatus[]] = ["draft","published","review"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.