import React from 'react';
import { getScores, type ScoreItem } from '../endpoints/scores_GET.schema';
import { Radio, ChevronRight, ShieldCheck, Clock3, TrendingUp } from 'lucide-react';
import styles from './_index.module.css';
const teams=[
{id:'canadiens',kicker:'MONTREAL CANADIENS',title:'Everything Habs. One home.',desc:'News, game coverage, roster moves, prospects, standings, highlights and verified trade reporting.',image:'https://media.d3.nhle.com/image/private/t_ratio16_9-size50/prd/ixpa55luihecrteuehqw.jpg'},
{id:'raptors',kicker:'TORONTO RAPTORS',title:'North basketball lives here.',desc:'Scores, schedule, standings, player leaders, injuries, transactions, highlights and analysis.',image:'https://cdn.nba.com/headshots/nba/latest/1040x760/1630567.png'},
{id:'bluejays',kicker:'TORONTO BLUE JAYS',title:'Canada’s baseball desk.',desc:'Scores, probable starters, standings, stats, transactions, prospects, highlights and analysis.',image:'https://img.mlbstatic.com/mlb-photos/image/upload/ar_40:21,g_auto,q_auto:good,w_1200,c_fill,f_jpg/v1/people/665489/action/vertical/current'}];
const desk=[
['TNESN LIVE','Game-day command centre','Scores, matchup cards, schedules and postgame coverage organized across all three teams.','https://media.d3.nhle.com/image/private/t_ratio16_9-size20/f_auto/prd/oyiel3dslhpijzolmvot.jpg','/canadiens'],
['VERIFIED NEWS','Firecrawl verification gate','Official-source reporting is verified before factual publication.','https://cdn.nba.com/headshots/nba/latest/1040x760/1630193.png','/coverage?team=raptors&section=news'],
['TRADE CENTRE','Rumours stay rumours','Reports are separated from confirmed transactions with source metadata.','https://img.mlbstatic.com/mlb-photos/image/upload/ar_40:21,g_auto,q_auto:good,w_1200,c_fill,f_jpg/v1/people/665926/action/vertical/current','/coverage?team=blue_jays&section=rumors'],
['TROPHY TRACKER','The championship race','Awards, team progress and sourced probability data with clear attribution.','https://media.d3.nhle.com/image/private/t_ratio16_9-size20/f_auto/prd/rmvgdtysufxwnf8znphe.jpg','/coverage?team=canadiens&section=trophies'],
['PROSPECTS','Future watch','Draft picks, development, call-ups and publicly reported scouting activity.','https://cdn.nba.com/headshots/nba/latest/1040x760/1641710.png','/coverage?team=canadiens&section=prospects'],
['HISTORY','The vault','Championships, legends, defining games and franchise timelines.','https://img.mlbstatic.com/mlb-photos/image/upload/ar_40:21,g_auto,q_auto:good,w_1200,c_fill,f_jpg/v1/people/672386/action/vertical/current','/coverage?team=blue_jays&section=awards']];
export default function Home(){const [scores,setScores]=React.useState<ScoreItem[]>([]);React.useEffect(()=>{getScores().then(x=>setScores(x.scores)).catch(()=>setScores([]))},[]);return <div className={styles.app}>
<section className={styles.scorebar}><div className={styles.live}><Radio size={15}/> LIVE SCOREBOARD</div><div className={styles.scoretrack}>{scores.length?scores.map((s,i)=><a className={styles.score} key={i} href={s.gameUrl||'#'} target={s.gameUrl?'_blank':undefined} rel={s.gameUrl?'noreferrer':undefined}><img src={s.awayLogo}/><b>{s.away}</b><strong>{s.awayScore}–{s.homeScore}</strong><b>{s.home}</b><img src={s.homeLogo}/><small>{s.league} • {s.status} • OPEN GAME</small></a>):<div className={styles.score}><b>TNESN</b><span>Loading live sports…</span></div>}</div></section>
<header className={styles.header}><div className={styles.brand}><img src="/_cdn/static/8bb13299-52e1-4421-9bcd-eaf37826e6c7-tnesn-logo.png" alt="TNESN True North East Sports Network"/><div><b>TRUE NORTH EAST</b><em>SPORTS NETWORK</em></div></div><nav><a href="#top">HOME</a><a href="/canadiens">CANADIENS</a><a href="/raptors">RAPTORS</a><a href="/blue-jays">BLUE JAYS</a><a href="#news">NEWS</a><a href="/store">STORE</a><a href="/community">COMMUNITY</a></nav></header>
<main id="top"><a className={styles.installAlert} href="/install" aria-label="Install the TNESN app"><span className={styles.phoneIcon}>📱</span><span className={styles.notifyBubble}>1</span><strong>GET THE TNESN APP</strong><span className={styles.textBubble}>Install from TNESN.COM</span></a><section className={styles.installBanner}><div><b>📲 GET THE TNESN APP</b><span>Install TNESN directly from TNESN.COM — no app store required.</span></div><a href="/install">📲 INSTALL APP</a></section><section className={styles.hero}><div className={styles.heroCopy}><div className={styles.eyebrow}><span>TNESN</span> CANADA'S THREE-TEAM SPORTS DESK</div><h1>THE GAMES.<br/>THE STORIES.<br/><i>THE NORTH.</i></h1><p>One independent destination built around Montreal Canadiens, Toronto Raptors and Toronto Blue Jays coverage.</p><div className={styles.verification}><ShieldCheck/><div><b>VERIFICATION-FIRST AUTO ENGINE</b><small>Official media • source checks • timestamps • review queue</small></div></div></div></section>
<section className={styles.teamGrid}>{teams.map(t=><article id={t.id} className={styles.teamCard} style={{backgroundImage:`linear-gradient(0deg,rgba(3,10,20,.94),rgba(3,10,20,.25)),url("${t.image}")`}} key={t.id}><small>{t.kicker}</small><h2>{t.title}</h2><p>{t.desc}</p><a href={t.id==='bluejays'?'/blue-jays':'/'+t.id}>ENTER TEAM HUB <ChevronRight/></a></article>)}</section>
	<section id="news" className={styles.news}><div className={styles.sectionHead}><div><span>TNESN DESK</span><h2>THE NETWORK</h2></div><p>Hockey • Basketball • Baseball</p></div><div className={styles.deskGrid}>{desk.map((d,i)=><a key={i} href={d[4]} style={{backgroundImage:`linear-gradient(0deg,rgba(4,11,22,.78),rgba(4,11,22,.06)),url("${d[3]}")`}}><TrendingUp/><small>{d[0]}</small><h3>{d[1]}</h3><p>{d[2]}</p><b>OPEN DESK →</b></a>)}</div></section>
<section id="trackers" className={styles.auto}><div><span>AUTO ENGINE</span><h2>VISIT → DISCOVER → VERIFY → PUBLISH</h2></div><div className={styles.flow}><b>01 VISIT CHECK</b><i>→</i><b>02 FIRECRAWL VERIFY</b><i>→</i><b>03 SOURCE + TIMESTAMP</b><i>→</i><b>04 PUBLISH / REVIEW</b></div><p>Unverified or conflicting factual information is routed to editorial review rather than presented as confirmed.</p></section></main>
<footer><b>TRUE NORTH EAST SPORTS NETWORK</b><span>Independent sports coverage • Montreal • Toronto • Canada</span><span><a href="/about">ABOUT</a> · <a href="/privacy">PRIVACY</a> · <a href="/terms">TERMS & EDITORIAL POLICY</a></span></footer></div>}