import React,{useEffect,useState} from 'react';
import {ThumbsUp,ThumbsDown,MessageCircle,Plus,ShieldCheck,Send} from 'lucide-react';
import {Button} from '../components/Button';import {Input} from '../components/Input';import {Textarea} from '../components/Textarea';
import {useAuth} from '../helpers/useAuth';import {getCommunityFeed,type CommunityPost} from '../endpoints/community/feed_GET.schema';import {postCommunityPost} from '../endpoints/community/post_POST.schema';import {postCommunityComment} from '../endpoints/community/comment_POST.schema';import {postCommunityReaction} from '../endpoints/community/react_POST.schema';import styles from './community.module.css';
const avatars:[string,string,string][]=[['hockey','🏒','HOCKEY'],['basketball','🏀','BASKETBALL'],['baseball','⚾','BASEBALL'],['trophy','🏆','TROPHY'],['microphone','🎙️','BROADCASTER'],['maple_leaf','🍁','CANADA']];
const icon=(key:string)=>avatars.find(a=>a[0]===key)?.[1]||'🏒';
export default function Community(){const {authState}=useAuth();const [posts,setPosts]=useState<CommunityPost[]>([]),[loading,setLoading]=useState(true),[composer,setComposer]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[comments,setComments]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);try{setPosts((await getCommunityFeed()).posts)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const create=async()=>{await postCommunityPost({title,body});setTitle('');setBody('');setComposer(false);await load()};
 const react=async(target:'post'|'comment',id:string,kind:'like'|'dislike')=>{if(authState.type!=='authenticated'){location.href='/login';return}await postCommunityReaction({target,id,kind});await load()};
 const comment=async(id:string)=>{const text=comments[id]?.trim();if(!text)return;await postCommunityComment({postId:id,body:text});setComments(x=>({...x,[id]:''}));await load()};
 return <main className={styles.page}><header><a href="/"><b>TN</b><span>TRUE NORTH EAST <i>COMMUNITY</i></span></a><nav><a href="/">HOME</a><a href="/community">COMMUNITY</a>{authState.type==='authenticated'?<strong>{authState.user.displayName}</strong>:<a className={styles.login} href="/login">LOG IN / JOIN</a>}</nav></header>
 <section className={styles.hero}><small>TNESN FAN ZONE</small><h1>THE NORTH HAS A VOICE.</h1><p>Talk Canadiens, Raptors and Blue Jays with the TNESN community.</p>{authState.type==='authenticated'?<Button onClick={()=>setComposer(!composer)}><Plus size={17}/> NEW POST</Button>:<Button asChild><a href="/login">LOG IN TO POST</a></Button>}</section>
 <section className={styles.grid}><div><div className={styles.head}><h2>LATEST DISCUSSIONS</h2><span>{posts.length} discussions</span></div>
 {composer&&<div className={styles.composer}><Input placeholder="Discussion title" value={title} onChange={e=>setTitle(e.target.value)}/><Textarea placeholder="What do you want to talk about?" value={body} onChange={e=>setBody(e.target.value)}/><Button disabled={title.trim().length<3||!body.trim()} onClick={create}>PUBLISH POST</Button></div>}
 {loading?<article className={styles.empty}><p>Loading the community…</p></article>:posts.length===0?<><article className={styles.empty}><MessageCircle/><h3>The community is ready.</h3><p>Create an account and start the first discussion.</p><a href="/login">JOIN TNESN COMMUNITY →</a></article><article className={styles.post}><div className={styles.author}><span>🏒</span><b>TNESN DESK</b><small>WELCOME</small></div><h3>What are you watching this week?</h3><p>Use the TNESN community to talk Canadiens, Raptors and Blue Jays. Game reactions, roster debates and prospect talk are all welcome.</p></article></>:posts.map(p=><article className={styles.post} key={p.id}><div className={styles.author}><span>{icon(p.avatarKey)}</span><b>{p.displayName}</b><small>{new Date(p.createdAt).toLocaleString()}</small></div><h3>{p.title}</h3><p>{p.body}</p><div className={styles.postActions}><button onClick={()=>react('post',p.id,'like')}><ThumbsUp/> {p.likes}</button><button onClick={()=>react('post',p.id,'dislike')}><ThumbsDown/> {p.dislikes}</button><span><MessageCircle/> {p.comments.length}</span></div>{p.comments.map(c=><div className={styles.comment} key={c.id}><span>{icon(c.avatarKey)}</span><div><b>{c.displayName}</b><p>{c.body}</p><button onClick={()=>react('comment',c.id,'like')}>👍 {c.likes}</button><button onClick={()=>react('comment',c.id,'dislike')}>👎 {c.dislikes}</button></div></div>)}{authState.type==='authenticated'&&<div className={styles.reply}><Input placeholder="Write a comment…" value={comments[p.id]||''} onChange={e=>setComments(x=>({...x,[p.id]:e.target.value}))}/><Button onClick={()=>comment(p.id)}><Send size={15}/></Button></div>}</article>)}</div>
 <aside><h3>YOUR SPORTS AVATAR</h3><p>Six profile identities are built into TNESN.</p><div className={styles.avatars}>{avatars.map(a=><div key={a[0]}><span>{a[1]}</span><small>{a[2]}</small></div>)}</div><div className={styles.rules}><ShieldCheck/><div><b>COMMUNITY STANDARD</b><p>Debate the play, not the person. Keep discussions focused on sports.</p></div></div></aside></section></main>}