import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ExternalLink,ShieldCheck,RefreshCw} from 'lucide-react';
import {getEditorialFeed,type EditorialCard} from '../endpoints/editorial/feed_GET.schema';
import styles from './coverage.module.css';

const teamNames:Record<string,string>={canadiens:'MONTRÉAL CANADIENS',raptors:'TORONTO RAPTORS',blue_jays:'TORONTO BLUE JAYS'};
const teamRoutes:Record<string,string>={canadiens:'/canadiens',raptors:'/raptors',blue_jays:'/blue-jays'};
const teamThumb:Record<string,string>={canadiens:'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',raptors:'https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg',blue_jays:'https://www.mlbstatic.com/team-logos/141.svg'};
const sectionNames:Record<string,string>={news:'NEWS',highlights:'HIGHLIGHTS',roster:'ROSTER + MOVES',prospects:'PROSPECTS',standings:'STANDINGS',trophies:'TROPHY TRACKER',awards:'AWARDS TRACKER',rumors:'TRADE RUMOURS'};
const official:Record<string,Record<string,string>>={
 canadiens:{news:'https://www.nhl.com/canadiens/news/',highlights:'https://www.nhl.com/canadiens/video/',roster:'https://www.nhl.com/canadiens/roster',prospects:'https://www.nhl.com/canadiens/news/',standings:'https://www.nhl.com/standings/',trophies:'https://www.nhl.com/canadiens/stats',rumors:'https://www.nhl.com/canadiens/news/'},
 raptors:{news:'https://www.nba.com/raptors/news',highlights:'https://www.nba.com/raptors/videos',roster:'https://www.nba.com/raptors/roster',standings:'https://www.nba.com/standings',trophies:'https://www.nba.com/raptors/stats',awards:'https://www.nba.com/raptors/stats',rumors:'https://www.nba.com/raptors/news'},
 blue_jays:{news:'https://www.mlb.com/bluejays/news',highlights:'https://www.mlb.com/bluejays/video',roster:'https://www.mlb.com/bluejays/roster',standings:'https://www.mlb.com/standings',prospects:'https://www.mlb.com/prospects/bluejays',awards:'https://www.mlb.com/bluejays/history/records-stats-awards/awards',trophies:'https://www.mlb.com/bluejays/stats',rumors:'https://www.mlb.com/bluejays/news'}
};
type LaunchCard={title:string;summary:string;sourceUrl:string;sourceName:string;sourcePublishedAt:string|null;isRumor?:boolean;imageUrl?:string};
const launchCards:Record<string,LaunchCard[]>={
 canadiens:[
 {title:'OTT-MTL: Game recaps | Preseason',summary:'Official Canadiens recap from the final preseason date.',sourceUrl:'https://www.nhl.com/canadiens/news/ott-mtl-game-recaps-preseason-sept-26-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-26T12:00:00Z'},
 {title:'Canadiens make roster moves at training camp',summary:'Official club roster-move update from training camp.',sourceUrl:'https://www.nhl.com/canadiens/news/canadiens-make-roster-moves-at-training-camp-sept-26-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-26T12:00:00Z'},
 {title:'Lines and defense pairings at morning skate – Sept. 26',summary:'Official game-day lines and defence pairings.',sourceUrl:'https://www.nhl.com/canadiens/news/lines-and-defense-pairings-at-morning-skate-sept-26-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-26T12:00:00Z'},
 {title:'OTT-MTL: What you need to know | Preseason',summary:'Official Canadiens game-day preview and notes.',sourceUrl:'https://www.nhl.com/canadiens/news/ott-mtl-what-you-need-to-know-preseason-sept-26-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-26T12:00:00Z'},
 {title:'Updates from training camp – Sept. 25',summary:'Official Canadiens training-camp update.',sourceUrl:'https://www.nhl.com/canadiens/news/updates-from-training-camp-sept-25-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-25T12:00:00Z'},
 {title:'Recap: 2026 Canadiens Training Camp scrimmage',summary:'Official recap of Montreal’s training-camp scrimmage.',sourceUrl:'https://www.nhl.com/canadiens/news/recap-2026-canadiens-training-camp-scrimmage-sept-24-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-24T12:00:00Z'},
 {title:'How to watch Canadiens Training Camp Scrimmage',summary:'Official viewing information and camp coverage.',sourceUrl:'https://www.nhl.com/canadiens/news/how-to-watch-canadiens-training-camp-scrimmage-sept-24-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-24T12:00:00Z'},
 {title:'Updates from training camp – Sept. 23',summary:'Official Canadiens camp notes and player updates.',sourceUrl:'https://www.nhl.com/canadiens/news/updates-from-training-camp-sept-23-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-23T12:00:00Z'},
 {title:'2026 Draft: How far the Canadiens have come',summary:'Official Canadiens prospect and development feature.',sourceUrl:'https://www.nhl.com/canadiens/news/2026-draft-how-far-the-canadiens-have-come-9-sept-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-22T12:00:00Z'},
 {title:'OTT-MTL: Game recap | Preseason',summary:'Official Canadiens preseason game recap.',sourceUrl:'https://www.nhl.com/canadiens/news/ott-mtl-game-recap-preseason-sept-21-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-21T12:00:00Z'},
 {title:'Lines and defense pairings at morning skate – Sept. 21',summary:'Official Canadiens lineup information.',sourceUrl:'https://www.nhl.com/canadiens/news/lines-and-defense-pairings-at-morning-skate-sept-21-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-21T12:00:00Z'},
 {title:'TOR-MTL: Game recaps | Preseason',summary:'Official Canadiens recap from the Toronto preseason matchup.',sourceUrl:'https://www.nhl.com/canadiens/news/tor-mtl-game-recaps-preseason-sept-19-2026',sourceName:'Montréal Canadiens / NHL',sourcePublishedAt:'2026-09-19T12:00:00Z'}
 ],
 raptors:[
 {title:'2026-27 Season Preview: Toronto Raptors',summary:'NBA.com season preview for Toronto entering 2026-27.',sourceUrl:'https://www.nba.com/news/2026-27-season-preview-tor',sourceName:'NBA.com',sourcePublishedAt:'2026-09-22T17:56:00Z'},
 {title:'Raptors acquire Kawhi Leonard from LA Clippers',summary:'Official NBA release covering Toronto’s trade for Kawhi Leonard.',sourceUrl:'https://www.nba.com/news/raptors-clippers-kawhi-leonard-trade',sourceName:'NBA.com',sourcePublishedAt:'2026-09-23T15:36:00Z'},
 {title:'Kawhi Leonard signs extension with Raptors',summary:'Official NBA release covering Leonard’s multi-year Toronto extension.',sourceUrl:'https://www.nba.com/news/kawhi-leonard-signs-multi-year-extension-raptors',sourceName:'NBA.com',sourcePublishedAt:'2026-09-25T01:18:00Z'},
 {title:'4 takeaways: Kawhi Leonard returns to Toronto',summary:'NBA.com analysis of the Raptors’ roster after the Leonard trade.',sourceUrl:'https://www.nba.com/news/4-takeaways-kawhi-leonard-returns-to-toronto-in-trade-with-clippers',sourceName:'NBA.com',sourcePublishedAt:'2026-09-16T00:25:00Z'},
 {title:'Raptors coaching staff finalized for 2026-27',summary:'Official NBA release on Toronto’s coaching staff.',sourceUrl:'https://www.nba.com/news/toronto-raptors-finalize-coaching-staff-2026-27',sourceName:'NBA.com',sourcePublishedAt:'2026-09-17T19:21:00Z'},
 {title:'Kyle Lowry receives Key to the City',summary:'NBA.com coverage of the honour for the Raptors legend.',sourceUrl:'https://www.nba.com/news/raptors-kyle-lowry-receives-key-to-the-city-in-toronto',sourceName:'NBA.com',sourcePublishedAt:'2026-09-19T20:38:00Z'},
 {title:'Live updates: 2026 NBA Media Days',summary:'NBA.com live coverage including Toronto Raptors Media Day.',sourceUrl:'https://www.nba.com/news/live-updates-2026-nba-media-days',sourceName:'NBA.com',sourcePublishedAt:'2026-09-28T12:43:00Z'},
 {title:'Scottie Barnes | Media Day',summary:'Official Raptors Media Day video with Scottie Barnes.',sourceUrl:'https://www.nba.com/raptors/videos/scottie-barnes-media-day-september-28-2026',sourceName:'Toronto Raptors / NBA',sourcePublishedAt:'2026-09-28T12:00:00Z',imageUrl:'https://cdn.nba.com/headshots/nba/latest/1040x760/1630567.png'},
 {title:'RJ Barrett | Media Day',summary:'Official Raptors Media Day video with RJ Barrett.',sourceUrl:'https://www.nba.com/raptors/videos/rj-barrett-media-day-september-28-2026',sourceName:'Toronto Raptors / NBA',sourcePublishedAt:'2026-09-28T12:00:00Z',imageUrl:'https://cdn.nba.com/headshots/nba/latest/1040x760/1629628.png'},
 {title:'Lowry Block Party | Full Media Availability',summary:'Official Raptors video from Kyle Lowry’s Block Party.',sourceUrl:'https://www.nba.com/raptors/videos/lowry-block-party-full-media-availability-september-19-2026',sourceName:'Toronto Raptors / NBA',sourcePublishedAt:'2026-09-19T12:00:00Z'},
 {title:'Danny Green | Lowry Block Party',summary:'Official Raptors video featuring Danny Green.',sourceUrl:'https://www.nba.com/raptors/videos/danny-green-lowry-block-party-september-19-2026',sourceName:'Toronto Raptors / NBA',sourcePublishedAt:'2026-09-19T12:00:00Z'},
 {title:'Toronto Raptors 2026-27 schedule',summary:'Official NBA schedule for Toronto, including preseason and regular season.',sourceUrl:'https://www.nba.com/team/1610612761/schedule',sourceName:'NBA.com',sourcePublishedAt:null}
 ],
 blue_jays:[
 {title:"Max Scherzer shines in Blue Jays' win",summary:'Official MLB game-recap video from September 27.',sourceUrl:'https://www.mlb.com/bluejays/video/max-scherzer-shines-in-blue-jays-win',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-27T12:00:00Z',imageUrl:'https://img.mlbstatic.com/mlb-photos/image/upload/w_640,q_auto:best,f_auto/v1/people/453286/headshot/67/current'},
 {title:"George Springer's possible final at-bat for Blue Jays",summary:'Official MLB video from the September 27 finale.',sourceUrl:'https://www.mlb.com/bluejays/video/george-springer-s-possible-final-at-bat-for-blue-jays',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-27T12:00:00Z',imageUrl:'https://img.mlbstatic.com/mlb-photos/image/upload/w_640,q_auto:best,f_auto/v1/people/543807/headshot/67/current'},
 {title:"John Schneider: Thank you",summary:'Official Blue Jays video following the season finale.',sourceUrl:'https://www.mlb.com/bluejays/video/john-schneider-thank-you',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-27T12:00:00Z'},
 {title:'George Springer receives standing ovation',summary:'Official MLB video from September 27.',sourceUrl:'https://www.mlb.com/bluejays/video/george-springer-receives-standing-ovation',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-27T12:00:00Z'},
 {title:'Max Scherzer pleads his case to stay in',summary:'Official MLB video from Scherzer’s September 27 outing.',sourceUrl:'https://www.mlb.com/bluejays/video/max-scherzer-pleads-his-case-to-stay-in',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-27T12:00:00Z'},
 {title:'Condensed Game: TOR@BAL Game 2 - 9/23/26',summary:'Official MLB condensed Blue Jays game.',sourceUrl:'https://www.mlb.com/bluejays/video/condensed-game-tor-bal-game-2-9-23-26',sourceName:'MLB.com',sourcePublishedAt:'2026-09-23T12:00:00Z'},
 {title:"John Schneider discusses Blue Jays' loss",summary:'Official Blue Jays postgame media video.',sourceUrl:'https://www.mlb.com/bluejays/video/john-schneider-discusses-blue-jays-loss-x5697',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-23T12:00:00Z'},
 {title:"Louis Varland seals Blue Jays' 7-3 win",summary:'Official MLB in-game highlight.',sourceUrl:'https://www.mlb.com/bluejays/video/louis-varland-seals-blue-jays-7-3-win',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-12T12:00:00Z'},
 {title:"Alejandro Kirk's two-run homer",summary:'Official MLB home-run highlight.',sourceUrl:'https://www.mlb.com/bluejays/video/alejandro-kirk-homers-10-on-a-fly-ball-to-left-center-field-george-spring',sourceName:'Toronto Blue Jays / MLB',sourcePublishedAt:'2026-09-12T12:00:00Z'},
 {title:'Condensed Game: TOR@ATH - 9/9/26',summary:'Official MLB condensed Blue Jays game.',sourceUrl:'https://www.mlb.com/bluejays/video/condensed-game-tor-ath-9-9-26',sourceName:'MLB.com',sourcePublishedAt:'2026-09-09T12:00:00Z'},
 {title:'Condensed Game: TOR@KC - 9/5/26',summary:'Official MLB condensed Blue Jays game.',sourceUrl:'https://www.mlb.com/bluejays/video/condensed-game-tor-kc-9-5-26',sourceName:'MLB.com',sourcePublishedAt:'2026-09-05T12:00:00Z'},
 {title:'Condensed Game: TOR@CLE - 9/1/26',summary:'Official MLB condensed Blue Jays game.',sourceUrl:'https://www.mlb.com/bluejays/video/condensed-game-tor-cle-9-1-26',sourceName:'MLB.com',sourcePublishedAt:'2026-09-01T12:00:00Z'}
 ]};
const fallbackCards:Record<string,Record<string,LaunchCard[]>>={
 canadiens:{
  news:[
   {title:'Official Canadiens news hub',summary:'Latest team news, game-day reporting, personnel moves and club updates from the Montréal Canadiens.',sourceUrl:'https://www.nhl.com/canadiens/news/',sourceName:'Montréal Canadiens',sourcePublishedAt:null},
   {title:'Canadiens acquire Sasha Pastujov',summary:'Montreal acquired forward Sasha Pastujov from Anaheim in exchange for Sean Farrell.',sourceUrl:'https://www.nhl.com/canadiens/news/canadiens-acquire-forward-sasha-pastujov-from-the-anaheim-ducks-july-27-2026',sourceName:'Montréal Canadiens PR',sourcePublishedAt:'2026-07-27T12:00:00Z'}
  ],
  highlights:[{title:'Official Canadiens video hub',summary:'Latest Canadiens highlights, interviews and team video from NHL.com.',sourceUrl:'https://www.nhl.com/canadiens/video/',sourceName:'NHL.com',sourcePublishedAt:null}],
  roster:[
   {title:'Montréal Canadiens 2026-27 roster',summary:'Official Canadiens roster with positions and player profile information.',sourceUrl:'https://www.nhl.com/canadiens/roster',sourceName:'NHL.com',sourcePublishedAt:null},
   {title:'Canadiens 2026-27 roster changes',summary:'NHL.com offseason roster overview for Montreal entering the 2026-27 season.',sourceUrl:'https://www.nhl.com/news/topic/team-resets/montreal-canadiens-roster-changes-for-2026-27-season',sourceName:'NHL.com',sourcePublishedAt:null}
  ],
  prospects:[{title:'Montréal Canadiens prospects',summary:'Official Canadiens prospect coverage, including rookie-camp and development updates.',sourceUrl:'https://www.nhl.com/canadiens/prospects',sourceName:'Montréal Canadiens',sourcePublishedAt:null},{title:'NHL prospects for 2026-27',summary:'NHL.com’s current league-wide prospect coverage for the 2026-27 season.',sourceUrl:'https://www.nhl.com/news/top-26-nhl-prospects-ranked-for-2026-2027-season',sourceName:'NHL.com',sourcePublishedAt:'2026-09-09T12:00:00Z'}],
  standings:[{title:'NHL standings',summary:'Current official NHL standings, including Montreal’s position.',sourceUrl:'https://www.nhl.com/standings/',sourceName:'NHL.com',sourcePublishedAt:null}],
  trophies:[{title:'Canadiens team stats',summary:'Official Canadiens player and team statistical leaders for awards and trophy tracking.',sourceUrl:'https://www.nhl.com/canadiens/stats',sourceName:'NHL.com',sourcePublishedAt:null},{title:'NHL EDGE: Kreider complements Montreal’s young core',summary:'NHL.com EDGE analysis of Chris Kreider’s fit with the Canadiens entering 2026-27.',sourceUrl:'https://www.nhl.com/news/topic/nhl-edge/edge-stats-outlook-chris-kreider-montreal-2026-2027',sourceName:'NHL.com',sourcePublishedAt:'2026-09-17T12:00:00Z'}],
  rumors:[{title:'Canadiens official news for transaction confirmation',summary:'Rumours remain labelled as rumours on TNESN until a move is confirmed by an authoritative source.',sourceUrl:'https://www.nhl.com/canadiens/news/',sourceName:'Montréal Canadiens',sourcePublishedAt:null,isRumor:true}]
 },
 raptors:{
  news:[{title:'Toronto Raptors official news',summary:'Latest Raptors team news and official club coverage.',sourceUrl:'https://www.nba.com/raptors',sourceName:'Toronto Raptors / NBA.com',sourcePublishedAt:null},{title:'Kawhi Leonard signs multi-year extension with Raptors',summary:'NBA.com reported Toronto signed Kawhi Leonard to a multi-year extension in his return season.',sourceUrl:'https://www.nba.com/news/kawhi-leonard-signs-multi-year-extension-raptors',sourceName:'NBA.com',sourcePublishedAt:'2026-09-23T12:00:00Z'},{title:'Kyle Lowry receives Key to the City in Toronto',summary:'NBA.com covered the city honour for longtime Raptors icon Kyle Lowry.',sourceUrl:'https://www.nba.com/news/raptors-kyle-lowry-receives-key-to-the-city-in-toronto',sourceName:'NBA.com',sourcePublishedAt:'2026-09-19T12:00:00Z'}],
  highlights:[{title:'Toronto Raptors videos',summary:'Official Raptors highlights, interviews and behind-the-scenes team videos.',sourceUrl:'https://www.nba.com/raptors/news-media/videos',sourceName:'Toronto Raptors / NBA.com',sourcePublishedAt:null}],
  roster:[{title:'Toronto Raptors team profile and roster',summary:'Official NBA team profile with roster, schedule and team information.',sourceUrl:'https://www.nba.com/stats/team/1610612761',sourceName:'NBA.com',sourcePublishedAt:null},{title:'Kawhi Leonard signs multi-year extension with Raptors',summary:'A current official roster move affecting Toronto’s 2026-27 lineup.',sourceUrl:'https://www.nba.com/news/kawhi-leonard-signs-multi-year-extension-raptors',sourceName:'NBA.com',sourcePublishedAt:'2026-09-23T12:00:00Z'}],
  standings:[{title:'NBA standings',summary:'Current official NBA standings for the Eastern Conference and league.',sourceUrl:'https://www.nba.com/standings',sourceName:'NBA.com',sourcePublishedAt:null}],
  trophies:[{title:'Toronto Raptors team stats',summary:'Official Raptors team and player statistics for awards and performance tracking.',sourceUrl:'https://www.nba.com/stats/team/1610612761/traditional',sourceName:'NBA.com',sourcePublishedAt:null},{title:'Kyle Lowry receives Key to the City in Toronto',summary:'A recent franchise honour for one of Toronto’s most decorated players.',sourceUrl:'https://www.nba.com/news/raptors-kyle-lowry-receives-key-to-the-city-in-toronto',sourceName:'NBA.com',sourcePublishedAt:'2026-09-19T12:00:00Z'}],
  awards:[{title:'Toronto Raptors performance leaders',summary:'Official Raptors team and player statistics for awards tracking.',sourceUrl:'https://www.nba.com/stats/team/1610612761/traditional',sourceName:'NBA.com',sourcePublishedAt:null},{title:'Kyle Lowry receives Key to the City in Toronto',summary:'NBA.com documented a major civic honour for the Raptors legend.',sourceUrl:'https://www.nba.com/news/raptors-kyle-lowry-receives-key-to-the-city-in-toronto',sourceName:'NBA.com',sourcePublishedAt:'2026-09-19T12:00:00Z'}],
  rumors:[{title:'Raptors transaction confirmation desk',summary:'TNESN keeps unconfirmed reports labelled as rumours; confirmed moves are linked to NBA.com or the Raptors’ official site.',sourceUrl:'https://www.nba.com/raptors',sourceName:'Toronto Raptors / NBA.com',sourcePublishedAt:null,isRumor:true}]
 },
 blue_jays:{
  news:[
   {title:'Toronto Blue Jays official news',summary:'Latest Blue Jays headlines and club reporting from MLB.com.',sourceUrl:'https://www.mlb.com/bluejays',sourceName:'MLB.com',sourcePublishedAt:null},
   {title:'Latest Blue Jays injuries and transactions',summary:'MLB.com’s running tracker for Toronto injuries and roster transactions.',sourceUrl:'https://www.mlb.com/news/blue-jays-injuries-and-roster-moves',sourceName:'MLB.com',sourcePublishedAt:'2026-09-28T12:00:00Z'}
  ],
  highlights:[{title:'Blue Jays video hub',summary:'Latest official Toronto Blue Jays game highlights and video.',sourceUrl:'https://www.mlb.com/bluejays/video',sourceName:'MLB.com',sourcePublishedAt:null}],
  roster:[{title:'Toronto Blue Jays roster',summary:'Official Blue Jays roster and player information.',sourceUrl:'https://www.mlb.com/bluejays/roster',sourceName:'MLB.com',sourcePublishedAt:null},{title:'Blue Jays transactions',summary:'Official Toronto roster transaction log from MLB.com.',sourceUrl:'https://www.mlb.com/bluejays/roster/transactions',sourceName:'MLB.com',sourcePublishedAt:null}],
  standings:[{title:'Blue Jays regular-season standings',summary:'Official MLB standings for Toronto in the 2026 season.',sourceUrl:'https://www.mlb.com/bluejays/standings/mlb',sourceName:'MLB.com',sourcePublishedAt:null},{title:'Blue Jays Wild Card standings',summary:'Official Wild Card positioning for Toronto.',sourceUrl:'https://www.mlb.com/bluejays/standings/wild-card/2026',sourceName:'MLB.com',sourcePublishedAt:null}],
  prospects:[{title:'Blue Jays Top 30 prospects',summary:'Official MLB Pipeline prospect coverage for Toronto.',sourceUrl:'https://www.mlb.com/prospects/bluejays',sourceName:'MLB.com',sourcePublishedAt:null}],
  awards:[{title:'Blue Jays awards history',summary:'Official Toronto Blue Jays franchise awards and records.',sourceUrl:'https://www.mlb.com/bluejays/history/records-stats-awards/awards',sourceName:'MLB.com',sourcePublishedAt:null}],
  trophies:[{title:'Blue Jays team stats',summary:'Official Toronto statistics for player and team performance tracking.',sourceUrl:'https://www.mlb.com/bluejays/stats',sourceName:'MLB.com',sourcePublishedAt:null}],
  rumors:[{title:'Blue Jays official news for transaction confirmation',summary:'TNESN keeps unconfirmed reports labelled as rumours until authoritative confirmation.',sourceUrl:'https://www.mlb.com/bluejays/news',sourceName:'MLB.com',sourcePublishedAt:null,isRumor:true}]
 }
};

export default function Coverage(){
 const q=useMemo(()=>new URLSearchParams(location.search),[]),team=q.get('team')||'canadiens',section=q.get('section')||'news';
 const [items,setItems]=useState<EditorialCard[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setItems((await getEditorialFeed(team,section)).items)}catch(e){setError(e instanceof Error?e.message:'Feed unavailable')}finally{setLoading(false)}};
 useEffect(()=>{load()},[team,section]);
 const cls=team==='raptors'?styles.raptors:team==='blue_jays'?styles.jays:styles.habs, officialUrl=official[team]?.[section];
 const thumb=teamThumb[team]||'';
 const cardThumb=(x:any)=>x.imageUrl||('/_api/editorial/thumbnail?url='+encodeURIComponent(x.sourceUrl));
 return <main className={styles.page+' '+cls}><header><a href={teamRoutes[team]||'/'}><ArrowLeft/> TEAM HUB</a><b>TNESN</b><a href="/">HOME</a></header>
 <section className={styles.hero}><small>{teamNames[team]||'TNESN'}</small><h1>{sectionNames[section]||'COVERAGE'}</h1><p>Current TNESN coverage. Confirmed factual items shown here have passed the verification gate.</p></section>
 <section className={styles.content}><div className={styles.status}><ShieldCheck/><div><b>VERIFIED FEED</b><span>Firecrawl primary • Parallel Search fallback • official league sources</span></div><button onClick={load}><RefreshCw/> REFRESH</button></div>
 {officialUrl&&<div className={styles.official}><div><b>OFFICIAL LIVE SOURCE</b><span>Use the league/team destination for the latest authoritative data while TNESN’s verified feed updates.</span></div><a href={officialUrl} target="_blank" rel="noreferrer">OPEN OFFICIAL SOURCE <ExternalLink/></a></div>}
 {loading?<div className={styles.empty}>Checking the latest verified coverage…</div>:error?<div className={styles.empty}>{error}</div>:<div className={styles.grid}>{(()=>{const base=[...items,...(fallbackCards[team]?.[section]||[]).map((x,i)=>({id:'fallback-'+i,title:x.title,summary:x.summary,sourceUrl:x.sourceUrl,sourceName:x.sourceName,sourcePublishedAt:x.sourcePublishedAt?new Date(x.sourcePublishedAt):null,verifiedAt:new Date(),verificationProvider:'official source',isRumor:!!x.isRumor,itemType:section}))];const seen=new Set(base.map(x=>x.sourceUrl));const supplements=(launchCards[team]||[]).filter(x=>!seen.has(x.sourceUrl)).map((x,i)=>({id:'launch-'+i,title:x.title,summary:x.summary,sourceUrl:x.sourceUrl,sourceName:x.sourceName,sourcePublishedAt:x.sourcePublishedAt?new Date(x.sourcePublishedAt):null,verifiedAt:new Date(),verificationProvider:'official league source',isRumor:!!x.isRumor,itemType:section,imageUrl:x.imageUrl}));return [...base,...supplements].slice(0,Math.max(12,base.length));})().map(x=><article key={x.id}>{cardThumb(x)&&<div className={styles.thumb}><img src={cardThumb(x)} alt={(x.title||teamNames[team])+' thumbnail'} loading="lazy" onError={(e)=>{e.currentTarget.src=thumb}}/></div>}<div className={styles.meta}><span>{x.isRumor?'RUMOUR':'VERIFIED SOURCE'}</span><time>{x.sourcePublishedAt?new Date(x.sourcePublishedAt).toLocaleDateString():'CURRENT OFFICIAL PAGE'}</time></div><h2>{x.title}</h2><p>{x.summary}</p><footer><small>{x.sourceName||'Official source'} • {items.length?'verified by '+(x.verificationProvider||'TNESN'):'official-source fallback'}</small><a href={x.sourceUrl} target="_blank" rel="noreferrer">SOURCE <ExternalLink/></a></footer></article>)}</div>}</section></main>
}